# sample round config

# number of players in each group or null if there's only one group
players_per_group: null

# starting x (asset) endowment for each player
x_endowment: 20
# scaling for x asset
x_currency_scale: 10
# bounds for x asset
x_bounds: [0, 50]

# starting y (cash) endowment for each player
y_endowment: 20
# scaling for y asset
y_currency_scale: 1000
# bounds for y asset
y_bounds: [0, 50]

trade_box_scale: 0.2

# function for calculating utility given a player's current x and y holdings
# this calculation is done after scaling, so x and y are fractional values
# this function has to be valid javascript (pre es6, meaning no '**' operator)
# all of the Math functions are available though
utility_function: "Math.sqrt(x) * Math.sqrt(y)"
# the maximum utility value which can be reached by a player
# this is used to scale displayed utility values when generating the heatmap
max_utility: 50

# the length of the round in seconds
period_length: 60
# the amount the page should wait after the period ends in seconds
post_round_delay: 30

# whether to draw the heatmap
heatmap_enabled: true
# whether to use static or dynamic utility grid. In order to use the dual grid, make this variable false.
static_grid_enabled: true

# this number determines the number of orders to display in the list.
# if it's 0 then all orders are shown, if -1 then only your own orders are shown.
# your own orders are always shown.
show_n_best_orders: 0
# this number determines the number of trades to display in the list. if it's 0, then all trades are shown.
show_n_most_recent_trades: 2
# if true, show only your own trades in the trade list
show_own_trades_only: false

# this config field enables partial equilibrium treatment on heatmap
# adds vertical lines at integer values of X and draws hashmarks where these lines intersect the current indifference curve
# IMPORTANT: when using this treatment, x_currency_scale should be set to 1, or heatmap will not behave as expected
use_partial_equilibrium: false

# this config field enables the visual order book. this displays the order book as a segmented line extending from
# the player's current bundle
show_market_on_heatmap: true

# this config field can be used to disable the order book display on the left side of the interface
# it replaces the bid/ask/trade boxes and their order inputs with a single box that shows the price/quantity of the
# proposed bid and allows players to enter it as an order
show_order_book: false

show_trade_dot: true

# this config field disables the user input entry for price and qty.
disable_input_entry: false

# mark whether a round is a practice round or not. if a round is marked as a practice round, a pause screen for discussion will be shown after
# the trading session is complete
is_practice: false

# these two numbers determine how payoffs will be calculated. the utility given by the player's initial endowment will be multiplied by the "initial" multiplier
# and their gains will be multiplied by the "gain" multiplier
payoff_gain_multiplier: 2
payoff_initial_multiplier: 1

# this field determines how each player will be assigne a role. this array should be the same length as the number
# of players in a group. players are assigned a role from this array based on their id_in_group
role_assignments: ["buyer", "seller", "buyer", "seller", "buyer", "seller"]

# this field determines role-specific overrides for config params. if a role is specified, any config params specified for it
# will override the params specified above
role_params:
  buyer:
    x_endowment: 10
    y_endowment: 20
  seller:
    x_endowment: 15
    y_endowment: 10
